[package]
name = "fdnix-search-lambda"
version = "0.1.0"
edition = "2021"
description = "Rust AWS Lambda for fdnix hybrid search with LanceDB"

[[bin]]
name = "bootstrap"
path = "src/main.rs"

[dependencies]
# AWS Lambda Runtime
lambda_runtime = "0.8"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

# AWS SDK
aws-config = { version = "1.1.7", features = ["behavior-version-latest", "rustls"] }
aws-sdk-bedrockruntime = { version = "1.103.0", features = ["rustls"] }

# JSON handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# LanceDB integration
lancedb = "0.15"
arrow = "53.0"

# Static linking for Lambda deployment
lzma-sys = { version = "*", features = ["static"] }

# Error handling and utilities
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

# HTTP and async utilities  
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }
futures-util = "0.3"

[build-dependencies]

[profile.release]
# Optimize for size and performance in Lambda environment
opt-level = "z"     # Optimize for size
lto = true          # Link-time optimization
codegen-units = 1   # Single codegen unit for better optimization
panic = "abort"     # Reduce binary size
strip = true        # Strip symbols

