[package]
name = "fdnix-search-lambda"
version = "0.1.0"
edition = "2021"
description = "Rust AWS Lambda for fdnix FTS-only search with SQLite"

[lib]
name = "fdnix_search_lambda"
path = "src/lib.rs"

[[bin]]
name = "bootstrap"
path = "src/main.rs"

[dependencies]
# AWS Lambda Runtime
lambda_runtime = "0.8"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

# JSON handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# SQLite integration
rusqlite = { version = "0.32", features = ["bundled"] }

# Static linking for Lambda deployment
lzma-sys = { version = "*", features = ["static"] }

# Error handling and utilities
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

# HTTP and async utilities  
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }
futures-util = "0.3"

[dev-dependencies]
tokio-test = "0.4"
mockall = "0.12"
rstest = "0.18"
tempfile = "3.8"
uuid = { version = "1.0", features = ["v4"] }

[build-dependencies]

[profile.release]
# Optimize for size and performance in Lambda environment
opt-level = "z"     # Optimize aggressively for size
lto = true          # Full link-time optimization
codegen-units = 1   # Single codegen unit for better optimization
panic = "abort"     # Reduce binary size
strip = true        # Strip symbols

