[package]
name = "fdnix-search-api"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.9"
lambda_runtime = "0.13"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"

