[project]
name = "fdnix-metadata-generator"
version = "0.2.0"
description = "Extracts nixpkgs metadata and writes to a DuckDB artifact (optional S3 upload)"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.34.0",
    "botocore>=1.34.0",
    "requests>=2.31.0",
    "duckdb>=0.10.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = []
