[project]
name = "fdnix-embedding-generator"
version = "0.1.0"
description = "Generates embeddings for nixpkgs packages using AWS Bedrock"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.34.0",
    "botocore>=1.34.0", 
    "numpy>=1.24.0",
    "requests>=2.31.0",
    "duckdb>=0.10.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = []
